menu:
    Blog: /
    Archive: /archives/
#    Categories: /categories/
    GitHub: //github.com/krimeshu
#    Stackoverflow:
    Rss: /atom.xml

favicon: /favicon.ico
logo: /icon-tech.png

# Comment
# e.g disqus: seansun
disqus:
livere: MTAyMC8zNDQzMi8xMDk2OQ==

# Analytics
# google-analytics:
# ga: UA-65933410-1
cnzz: true

# Copyright Infomation
startyear: 2017
